#!/usr/bin/perl
use esmith::Build::CreateLinks qw(:all);

my $event = "nethserver-ddclient-update";
event_actions($event, 
'initialize-default-databases' => '00');

templates2events("/etc/ddclient/ddclient.conf", $event);

event_services($event, 'ddclient' => 'restart');
