#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use esmith::event;
use JSON;
use NethServer::ApiTools;

my $eventName = 'nethserver-ddclient-update';
my $ret;
my @eventArgs;

my $db = esmith::ConfigDB->open('dyndns');
my $input = NethServer::ApiTools::readInput();

if (!$input->{'name'}) {
    NethServer::ApiTools::error();
}

my $record = $db->get($input->{'name'});
$record->delete();

esmith::event::set_json_log(1);

if(esmith::event::event_signal($eventName, @eventArgs)) {
    NethServer::ApiTools::success();
} else {
    NethServer::ApiTools::error("EventError", "delete_action_failed", 1559997785);
}

print encode_json($ret);
