#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;
use NethServer::ApiTools;

my $input = NethServer::ApiTools::readInput();
my $cmd = $input->{'action'};

my $ret = {};

if ($cmd eq 'dyndns') {

    my @dyndns;
    my $ddb = esmith::ConfigDB->open_ro('dyndns');
    foreach ($ddb->get_all_by_prop('type'=>'dyndns')) {
        my %props = $_->props();
        delete($props{'type'});
        $props{'name'} = $_->key;
        push(@dyndns, \%props);
    }
    $ret->{'dyndns'} = \@dyndns;

} elsif ($cmd eq 'configuration') {
    my $db = esmith::ConfigDB->open_ro();
    my %dyndns = (
        DeamonUpdate => $db->get_prop('ddclient','DeamonUpdate'),
        SSL => $db->get_prop('ddclient','SSL'),
        urlcheckip => $db->get_prop('ddclient','urlcheckip'),
        status => $db->get_prop('ddclient','status')
    );
    $ret->{'configuration'} = \%dyndns;
} else {
    NethServer::ApiTools::error();
}

print encode_json($ret);
